classdef taxi_planning_counter
    %Mealy transducer Modified Version.
    %Internal states are integers, the current state
    %is stored in the attribute "state".
    %To take a transition, call method "move".

    %Automatically generated by tulip.dumpsmach on 2015-07-09 22:00:00 UTC
    %To learn more about TuLiP, visit http://tulip-control.org

    properties
        state
        loc
        full
    end

    methods
        function obj = taxi_planning_counter()
            obj.state = 7;
            obj.loc= 0; 
            obj.full= 0; 
        end

        function obj = move(obj, env_actions)
        %Given inputs, take move and return outputs.

        %@rtype: dict
        %@return: dictionary with keys of the output variable names:
        %    ['loc', 'full']
        
        if obj.state == 0
            if (strcmp(env_actions,'none'))
                obj.state = 0;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'pick'))
                obj.state = 1;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 1
            if (strcmp(env_actions,'none'))
                obj.state = 0;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'pick'))
                obj.state = 1;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 2
            if (strcmp(env_actions,'pick'))
                obj.state = 1;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'none'))
                obj.state = 2;
                obj.loc = 1;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 3
            if (strcmp(env_actions,'pick'))
                obj.state = 1;
                obj.loc = 2;
                obj.full = 1;
            elseif (strcmp(env_actions,'none'))
                obj.state = 2;
                obj.loc = 1;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 4
            if (strcmp(env_actions,'pick'))
                obj.state = 3;
                obj.loc = 1;
                obj.full = 0;
            elseif (strcmp(env_actions,'none'))
                obj.state = 4;
                obj.loc = 0;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 5
            if (strcmp(env_actions,'pick'))
                obj.state = 3;
                obj.loc = 1;
                obj.full = 0;
            elseif (strcmp(env_actions,'none'))
                obj.state = 4;
                obj.loc = 0;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 6
            if (strcmp(env_actions,'pick'))
                obj.state = 3;
                obj.loc = 1;
                obj.full = 0;
            elseif (strcmp(env_actions,'none'))
                obj.state = 4;
                obj.loc = 0;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        elseif obj.state == 7
            if (strcmp(env_actions,'none'))
                obj.state = 4;
                obj.loc = 0;
                obj.full = 0;
            elseif (strcmp(env_actions,'pick'))
                obj.state = 5;
                obj.loc = 0;
                obj.full = 0;
            elseif (strcmp(env_actions,'des'))
                obj.state = 6;
                obj.loc = 0;
                obj.full = 0;
            else
                display('Unrecognized input.');
            end
        else
            display('Unrecognized internal state.');
        end
        end

    end
end